//
export class UtilManager
{
    //
    static DebugHostingContent(msg : string) : string {
        //
        let regEx   = /(.*)(<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->)(.*\w+.*)(<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->)(.*)/;
        //
        let strMsg  = msg.replace(/(\r\n|\n|\r)/gm, "");
        //
        let matches = strMsg.match(regEx);
        //
        if (matches != null) {
            //
            for (var index = 1; index < matches.length; index++) {
                //
                var matchValue = matches[index];
                //        
                // //console.log("coincidencia : " + matchValue);
                //
                if ((matchValue.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->") != -1) && (matchValue.trim() != "")) {
                    //
                    strMsg = strMsg.replace(matchValue, "");
                }
                //
                if ((matchValue.indexOf("<center>") != -1) && (matchValue.trim() != "")) {
                    //
                    strMsg = strMsg.replace(matchValue, "");
                }
            }
            }
            else {
            //
            //console.log("NO_HAY_COINCIDENCIAS");
            }
            //
            return strMsg;
    };
}